version: "3.1"

services:
  application:
    container_name: shopif_web
    build: .
    #vcommand: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
    volumes:
      - ./code:/code
    ports:
      - "8002:8000"
  database:
    container_name: shopif_db
    image: postgres:16.3
    environment:
      POSTGRES_DB: shopif_db
      POSTGRES_USER: shopif_user
      POSTGRES_PASSWORD: shopif_password
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - "5536:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata