# Generated by Django 5.0.3 on 2024-07-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='deleted_at',
            new_name='updated_at',
        ),
    ]
